all:
	
	gcc -g -c compressor.c
	gcc -g -c functions.c
	gcc -g -o compressor functions.c compressor.o -lm

# For some reason maybe the 'make run' command will not work. Please, run manually by 
# entering './compressor' command on your terminal
run:

	./compressor

teste:

	gcc -g -c teste.c
	gcc -g -c functions.c
	gcc -g -o teste functions.c teste.o -lm